import { Eye, EyeOff, Info, Lightbulb, X } from 'lucide-react';
import { useRef, useState, type PointerEvent } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { useApi } from '../hooks/useApi';
import type { Hotspot } from '../types';
import { ErrorState, Loading, SectionTitle } from '../components/Ui';
import { useProgress } from '../context/ProgressContext';

function BuildingDetailed(){return <div className="architecture-art" role="img" aria-label="Minh họa mặt tiền Bến Nhà Rồng"><div className="arch-sky"/><div className="arch-roof"><i/><i/></div><div className="arch-body"><div className="arch-clock"/>{Array.from({length:9}).map((_,i)=><span key={i}/>)}</div><div className="arch-ground"/><div className="arch-river"/></div>}
export default function ArchitecturePage(){const{data,error,loading}=useApi<Hotspot[]>('/hotspots');const[active,setActive]=useState<Hotspot|null>(null);const[torch,setTorch]=useState(false);const scene=useRef<HTMLDivElement>(null);const{progress,mark}=useProgress();const move=(e:PointerEvent)=>{const box=scene.current?.getBoundingClientRect();if(box){scene.current?.style.setProperty('--mx',`${e.clientX-box.left}px`);scene.current?.style.setProperty('--my',`${e.clientY-box.top}px`);}};const open=(h:Hotspot)=>{setActive(h);mark('hotspots',h.id);if(progress.hotspots.length>=7)mark('badges','architect');};if(loading)return<div className="page-state"><Loading/></div>;if(error||!data)return<div className="page-state"><ErrorState message={error||'Không có dữ liệu'}/></div>;return<div className="content-page architecture-page"><SectionTitle eyebrow="KHÁM PHÁ KIẾN TRÚC" title="Đọc một công trình bằng ánh sáng" text="Chạm vào các điểm đánh dấu để quan sát những chi tiết tạo nên diện mạo Nhà Rồng."/><div className="architecture-toolbar"><button className={torch?'active primary-btn':'secondary-btn'} onClick={()=>setTorch(!torch)}>{torch?<EyeOff/>:<Lightbulb/>}{torch?'Tắt đèn khám phá':'Bật đèn khám phá'}</button><span><Eye/> {progress.hotspots.length}/8 chi tiết đã xem</span></div><div ref={scene} onPointerMove={move} className={`architecture-scene ${torch?'torch-on':''}`}><BuildingDetailed/>{data.map((h,i)=><button aria-label={`Khám phá ${h.title}`} onClick={()=>open(h)} className={`hotspot ${progress.hotspots.includes(h.id)?'visited':''}`} style={{left:`${h.x}%`,top:`${h.y}%`}} key={h.id}><span>{i+1}</span></button>)}<div className="torch-mask"/></div><AnimatePresence>{active&&<motion.aside className="architecture-info" initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} exit={{opacity:0,x:30}}><button className="icon-btn" onClick={()=>setActive(null)} aria-label="Đóng"><X/></button><Info/><span className="overline">CHI TIẾT {String(data.indexOf(active)+1).padStart(2,'0')}</span><h2>{active.title}</h2><p>{active.text}</p></motion.aside>}</AnimatePresence><p className="disclaimer">Đây là trải nghiệm trực quan phục vụ giáo dục, không thay thế hồ sơ hoặc bản vẽ kiến trúc chính thức.</p></div>}
