import { ArrowDown, ArrowRight, BookOpen, Map, MousePointer2, Ship, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect, useRef, useState } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { motion } from 'framer-motion';
import { useProgress } from '../context/ProgressContext';

gsap.registerPlugin(ScrollTrigger);
function BuildingSilhouette({ modern = false }: { modern?: boolean }) { return <div className={`building-art ${modern?'modern':''}`} aria-label="Minh họa Bến Nhà Rồng"><div className="roof-line"><i/><i/></div><div className="main-block"><span/><span/><span/><span/><span/></div><div className="stairs"/></div>; }
export default function HomePage() {
  const root = useRef<HTMLDivElement>(null); const [compare, setCompare] = useState(55); const { completion, mark } = useProgress();
  useEffect(() => { const ctx = gsap.context(() => { gsap.from('.hero-copy > *', { y: 40, opacity: 0, duration: 1, stagger: .14, ease: 'power3.out' }); gsap.utils.toArray<HTMLElement>('.story-reveal').forEach((el) => gsap.from(el, { scrollTrigger: { trigger: el, start: 'top 78%' }, y: 70, opacity: 0, duration: 1 })); gsap.to('.story-ship', { scrollTrigger: { trigger: '.departure-scene', start: 'top bottom', end: 'bottom top', scrub: 1 }, x: '65vw', scale: .7 }); gsap.to('.route-line', { scrollTrigger: { trigger: '.map-transition', start: 'top 70%', end: 'bottom 60%', scrub: 1 }, width: '78%' }); }, root); return () => ctx.revert(); }, []);
  const start = () => { mark('badges','first-step'); document.querySelector('#story')?.scrollIntoView({behavior:'smooth'}); };
  return <div ref={root} className="home-page">
    <section className="hero cinematic"><div className="sky-glow"/><div className="mist mist-one"/><div className="mist mist-two"/><BuildingSilhouette/><div className="water"><i/><i/><i/></div><div className="hero-copy"><span className="overline">SÀI GÒN · 05 THÁNG 06 · 1911</span><h1><small>TỪ</small> BẾN NHÀ RỒNG</h1><p>Một bến cảng – Một chuyến đi – Một hành trình lịch sử</p><button className="primary-btn" onClick={start}>Bắt đầu hành trình <ArrowRight/></button></div><a className="scroll-cue" href="#story"><span>Cuộn để khám phá</span><ArrowDown/></a><div className="grain"/></section>
    <section id="story" className="story scene-port"><div className="scene-number">01</div><div className="story-reveal narrow"><span className="overline">SÀI GÒN ĐẦU THẾ KỶ XX</span><h2>Nơi dòng sông gặp những chân trời</h2><p>Bên thương cảng Sài Gòn, Nhà Rồng đứng giữa nhịp giao thương đường biển. Công trình được xây dựng trong giai đoạn 1862–1863, mang bố cục kiến trúc Pháp và những chi tiết trang trí gợi hình tượng Việt Nam.</p><Link to="/architecture" className="text-link">Nhìn kỹ kiến trúc <ArrowRight/></Link></div><div className="port-lines" aria-hidden="true"/></section>
    <section className="story departure-scene"><div className="date-monument"><span>05</span><b>06</b><em>1911</em></div><div className="story-reveal departure-copy"><span className="overline">KHOẢNH KHẮC RỜI BẾN</span><h2>Một chuyến đi bắt đầu</h2><p>Ngày 05/06/1911, người thanh niên Nguyễn Tất Thành, với tên Văn Ba, rời Bến Nhà Rồng trên tàu Amiral Latouche Tréville. Công việc phụ bếp là phương tiện để Người đi, quan sát và tìm một con đường giải phóng dân tộc.</p><small>Nguồn: Bảo tàng Hồ Chí Minh; Cổng thông tin điện tử Hồ Chí Minh.</small></div><div className="story-ship"><Ship/><span/></div><div className="wake"/></section>
    <section className="story map-transition"><div className="world-orbit"><i/><i/><i/><i/><div className="route-line"/><Ship/></div><div className="story-reveal narrow"><span className="overline">TỪ DÒNG SÔNG RA THẾ GIỚI</span><h2>Những cảng biển mở ra một cách nhìn mới</h2><p>Singapore. Colombo. Port Said. Marseille. Những địa danh trên chặng biển đầu tiên không chỉ là tọa độ—đó là những ô cửa dẫn ra một thế giới rộng lớn.</p><Link to="/journey" className="primary-btn">Mở bản đồ hành trình <Map/></Link></div></section>
    <section className="story consciousness"><div className="story-reveal chapter"><span>1911–1917</span><h3>Quan sát thế giới</h3><p>Qua nhiều châu lục, trải nghiệm đời sống của người lao động và các dân tộc thuộc địa.</p></div><div className="story-reveal chapter"><span>1919</span><h3>Cất tiếng nói</h3><p>Tại Paris, Nguyễn Ái Quốc gửi Bản Yêu sách của nhân dân An Nam tới Hội nghị Versailles.</p></div><div className="story-reveal chapter"><span>1920</span><h3>Xác định con đường</h3><p>Một bước ngoặt quan trọng trong quá trình hình thành con đường giải phóng dân tộc.</p></div></section>
    <section className="story compare-scene"><div className="story-reveal compare-copy"><span className="overline">BẾN NHÀ RỒNG QUA THỜI GIAN</span><h2>Một công trình, nhiều lớp ký ức</h2><p>Kéo thanh để chuyển giữa ký ức thương cảng và không gian bảo tàng hôm nay.</p></div><div className="compare-frame"><div className="compare-old"><BuildingSilhouette/><b>1863</b></div><div className="compare-new" style={{clipPath:`inset(0 0 0 ${compare}%)`}}><BuildingSilhouette modern/><b>HÔM NAY</b></div><input aria-label="So sánh xưa và nay" type="range" min="5" max="95" value={compare} onChange={(e)=>setCompare(Number(e.target.value))}/><span className="compare-handle" style={{left:`${compare}%`}}><MousePointer2/></span></div></section>
    <section className="finale"><div className="lanterns"/><BuildingSilhouette modern/><motion.div className="final-copy" initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><Sparkles/><p>Từ một bến cảng,</p><h2>một hành trình lịch sử đã bắt đầu.</h2><div className="final-actions"><Link to="/journey" className="primary-btn">Bản đồ hành trình <ArrowRight/></Link><Link to="/museum" className="secondary-btn">Bảo tàng số <BookOpen/></Link></div><div className="completion-ring" style={{'--completion':`${completion * 3.6}deg`} as React.CSSProperties}><b>{completion}%</b><span>đã khám phá</span></div></motion.div></section>
  </div>;
}
