import { ArrowRight, CalendarDays, Filter } from 'lucide-react';
import { useState } from 'react';
import { motion } from 'framer-motion';
import { useApi } from '../hooks/useApi';
import type { EventItem } from '../types';
import { ErrorState, ImageWithFallback, Loading, SectionTitle } from '../components/Ui';
import { useProgress } from '../context/ProgressContext';

const cats=['Tất cả','Kiến trúc','Lịch sử','Hành trình','Bảo tàng'];
export default function TimelinePage(){const{data,error,loading}=useApi<EventItem[]>('/events');const[cat,setCat]=useState('Tất cả');const[selected,setSelected]=useState<EventItem|null>(null);const{mark}=useProgress();if(loading)return<div className="page-state"><Loading/></div>;if(error||!data)return<div className="page-state"><ErrorState message={error||'Không có dữ liệu'}/></div>;const filtered=data.filter(e=>cat==='Tất cả'||e.category===cat);const open=(e:EventItem)=>{setSelected(e);mark('timelineEvents',e.id);if(e.id==='today')mark('badges','timekeeper');};return<div className="content-page timeline-page"><SectionTitle eyebrow="DÒNG THỜI GIAN" title="Những lớp thời gian bên sông" text="Từ trụ sở một hãng vận tải đến không gian bảo tàng và ký ức đô thị."/><div className="filter-row"><Filter/>{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="timeline-track">{filtered.map((e,i)=><motion.button initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:i*.06}} onClick={()=>open(e)} className={`timeline-node ${selected?.id===e.id?'active':''}`} key={e.id}><span>{e.year}</span><i/><h3>{e.title}</h3><p>{e.summary}</p><b>Xem chi tiết <ArrowRight/></b></motion.button>)}</div>{selected&&<motion.section className="timeline-detail" initial={{opacity:0}} animate={{opacity:1}}><ImageWithFallback src={selected.image} alt={selected.title}/><div><span className="overline">{selected.category} · {selected.year}</span><h2>{selected.title}</h2><p>{selected.detail}</p><small>Nguồn: {selected.sourceId}</small></div></motion.section>} {!selected&&<div className="timeline-prompt"><CalendarDays/><p>Chọn một mốc để mở lớp tư liệu.</p></div>}</div>}
