import { Anchor, BookOpen, Building2, Compass, Headphones, Landmark, Menu, Moon, Route, ScrollText, Sun, TicketCheck, X } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { NavLink, Outlet, useLocation } from 'react-router-dom';
import { useEffect, useRef, useState } from 'react';
import { useProgress } from '../context/ProgressContext';

const links = [
  ['/', 'Trải nghiệm', Anchor], ['/journey', 'Hành trình', Route], ['/timeline', 'Dòng thời gian', ScrollText], ['/architecture', 'Kiến trúc', Building2], ['/museum', 'Bảo tàng số', Landmark], ['/quiz', 'Tương tác', BookOpen], ['/passport', 'Hộ chiếu', TicketCheck], ['/reflections', 'Cảm nhận', Compass], ['/sources', 'Nguồn', BookOpen]
] as const;
export default function Layout() {
  const [menu, setMenu] = useState(false); const [dark, setDark] = useState(true); const [sound, setSound] = useState(false); const [scroll,setScroll]=useState(0); const audio=useRef<AudioContext|null>(null); const location = useLocation(); const { completion, mark } = useProgress();
  useEffect(() => { setMenu(false); mark('visitedPages', location.pathname); window.scrollTo({ top: 0 }); const names: Record<string,string> = {'/':'Trải nghiệm','/journey':'Bản đồ hành trình','/timeline':'Dòng thời gian','/architecture':'Kiến trúc','/museum':'Bảo tàng số','/quiz':'Trắc nghiệm','/passport':'Hộ chiếu','/reflections':'Cảm nhận','/sources':'Nguồn tham khảo'}; const descriptions:Record<string,string>={'/':'Hành trình điện ảnh tương tác từ Bến Nhà Rồng và ngày 05/06/1911.','/journey':'Bản đồ các địa điểm tiêu biểu trong hành trình lịch sử.','/timeline':'Các lớp thời gian của Bến Nhà Rồng từ năm 1863 đến nay.','/architecture':'Khám phá trực quan kiến trúc Bến Nhà Rồng.','/museum':'Gallery tư liệu số theo năm phòng chủ đề.','/quiz':'Trắc nghiệm và trò chơi lịch sử tương tác.','/passport':'Hộ chiếu số lưu dấu tiến độ khám phá.','/reflections':'Lưu bút cảm nhận của khách tham quan.','/sources':'Nguồn lịch sử và hình ảnh sử dụng trong dự án.'}; document.title = `${names[location.pathname] || 'Không tìm thấy'} | TỪ BẾN NHÀ RỒNG`; document.querySelector('meta[name="description"]')?.setAttribute('content',descriptions[location.pathname]||'TỪ BẾN NHÀ RỒNG'); }, [location.pathname, mark]);
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; }, [dark]);
  useEffect(()=>{const update=()=>setScroll(Math.min(100,window.scrollY/Math.max(1,document.documentElement.scrollHeight-window.innerHeight)*100));window.addEventListener('scroll',update,{passive:true});update();return()=>window.removeEventListener('scroll',update)},[]);
  useEffect(()=>{if(!sound){audio.current?.close();audio.current=null;return}const context=new AudioContext();const gain=context.createGain();const oscillator=context.createOscillator();const filter=context.createBiquadFilter();oscillator.type='sine';oscillator.frequency.value=72;filter.type='lowpass';filter.frequency.value=180;gain.gain.value=.018;oscillator.connect(filter).connect(gain).connect(context.destination);oscillator.start();audio.current=context;return()=>{oscillator.stop();context.close();audio.current=null}},[sound]);
  return <div className="site-shell">
    <header className="topbar"><div className="scroll-progress" style={{width:`${scroll}%`}}/><NavLink to="/" className="brand" aria-label="Trang chủ Từ Bến Nhà Rồng"><span className="brand-mark"><Building2/></span><span><b>TỪ BẾN NHÀ RỒNG</b><small>Một hành trình lịch sử</small></span></NavLink>
      <nav className="desktop-nav" aria-label="Điều hướng chính">{links.slice(0,7).map(([to,label,Icon])=><NavLink key={to} to={to} className={({isActive})=>isActive?'active':''}><Icon/><span>{label}</span></NavLink>)}</nav>
      <div className="header-actions"><div className="progress-pill" title={`${completion}% đã khám phá`}><span style={{width:`${completion}%`}}/><b>{completion}%</b></div><button className="icon-btn" onClick={()=>setSound(!sound)} aria-label={sound?'Tắt âm thanh':'Bật âm thanh'}><Headphones className={sound?'active-icon':''}/></button><button className="icon-btn" onClick={()=>setDark(!dark)} aria-label={dark?'Bật giao diện sáng':'Bật giao diện tối'}>{dark?<Sun/>:<Moon/>}</button><button className="icon-btn menu-btn" onClick={()=>setMenu(!menu)} aria-label="Mở menu">{menu?<X/>:<Menu/>}</button></div>
    </header>
    <AnimatePresence>{menu&&<motion.nav className="mobile-nav" aria-label="Điều hướng di động" initial={{opacity:0,y:-15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}}>{links.map(([to,label,Icon])=><NavLink key={to} to={to}><Icon/>{label}</NavLink>)}</motion.nav>}</AnimatePresence>
    <AnimatePresence mode="wait"><motion.main key={location.pathname} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.28}}><Outlet/></motion.main></AnimatePresence>
    <footer><div><Building2/><h2>TỪ BẾN NHÀ RỒNG</h2><p>Một bến cảng – Một chuyến đi – Một hành trình lịch sử</p></div><nav>{links.slice(1).map(([to,label])=><NavLink key={to} to={to}>{label}</NavLink>)}</nav><small>Dự án trải nghiệm số phục vụ mục đích giáo dục · © {new Date().getFullYear()}</small></footer>
  </div>;
}
